import 'package:amazon_clone/core/models/products.dart';
import 'package:amazon_clone/core/services/preference_service.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../core/notifiers/home_notifiers.dart';

final tabProvider = StateNotifierProvider<TabNotifier, TabController?>((ref) {
  return TabNotifier();
});

final currentIndexProvider = StateProvider<int>((ref) => 0);

final isDarkModeProvider = StateNotifierProvider<ThemeNotifier, bool>((ref) {
  return ThemeNotifier(ref.watch(preferenceServiceProvider));
});

final productProvider = Provider<List<Product>>((ref) {
  return [
    const Product(
      id: '1',
      name: 'Stainless Steel Water Bottle',
      price: 24.99,
      imageUrl: 'assets/images/bottle.PNG',
      category: 'Accessories',
      rating: 4.6,
      description: 'Durable stainless steel water bottle with insulation for temperature retention.',
      brand: 'HydroPro',
      model: 'HP-Insulated',
      dimensions: '25x8x8 cm',
      weight: 0.6,
    ),
    const Product(
      id: '2',
      name: 'Action Camera',
      price: 249.99,
      imageUrl: 'assets/images/camera.jpg',
      category: 'Electronics',
      rating: 4.8,
      description: 'Compact action camera with 4K resolution and waterproof design.',
      brand: 'AdventureCam',
      model: 'AC-Pro4K',
      dimensions: '8x6x4 cm',
      weight: 0.3,
    ),
    const Product(
      id: '3',
      name: 'Ergonomic Office Chair',
      price: 149.99,
      imageUrl: 'assets/images/chair.jpeg',
      category: 'Furniture',
      rating: 4.4,
      description: 'Comfortable office chair with lumbar support for extended work sessions.',
      brand: 'ErgoPro',
      model: 'EP-Comfort',
      dimensions: '120x60x60 cm',
      weight: 12.0,
    ),
    const Product(
      id: '4',
      name: 'Non-Stick Cookware Set',
      price: 99.99,
      imageUrl: 'assets/images/cookware.jpg',
      category: 'Home & Kitchen',
      rating: 4.7,
      description: 'Premium non-stick cookware set designed for efficient cooking.',
      brand: 'ChefMaster',
      model: 'CM-Deluxe',
      dimensions: '40x30x20 cm',
      weight: 5.0,
    ),
    const Product(
      id: '5',
      name: 'Fiction Novel',
      price: 19.99,
      imageUrl: 'assets/images/fiction_novel.jpeg',
      category: 'Books',
      rating: 4.8,
      description: 'A captivating fiction novel filled with mystery and suspense.',
      brand: 'Mystic Reads',
      model: 'Edition 2',
      dimensions: '21x14x2 cm',
      weight: 0.3,
    ),
    const Product(
      id: '6',
      name: 'Stylish Sunglasses with UV Protection',
      price: 89.99,
      imageUrl: 'assets/images/glasses.jpeg',
      category: 'Fashion',
      rating: 4.5,
      description: 'Premium sunglasses designed for UV protection and style.',
      brand: 'VisionLux',
      model: 'VL-Shade',
      dimensions: '15x5x3 cm',
      weight: 0.25,
    ),
    const Product(
      id: '7',
      name: 'Wireless Headphones',
      price: 99.99,
      imageUrl: 'assets/images/headphones.jpeg',
      category: 'Electronics',
      rating: 4.5,
      description: 'Premium wireless headphones with active noise cancellation and deep bass.',
      brand: 'AudioTech',
      model: 'AT-X100',
      dimensions: '15x8x3 cm',
      weight: 0.5,
    ),
    const Product(
      id: '8',
      name: 'Electric Kettle',
      price: 39.99,
      imageUrl: 'assets/images/kettle.jpg',
      category: 'Home & Kitchen',
      rating: 4.3,
      description: 'Fast-boiling electric kettle with auto shut-off and temperature control.',
      brand: 'KitchenEase',
      model: 'KE-FastBoil',
      dimensions: '25x15x15 cm',
      weight: 1.0,
    ),
    const Product(
      id: '9',
      name: 'Gaming Laptop',
      price: 1299.99,
      imageUrl: 'assets/images/laptop.jpeg',
      category: 'Computers',
      rating: 4.6,
      description: 'High-performance gaming laptop with advanced graphics and fast refresh rate.',
      brand: 'GamerTech',
      model: 'GT-5000',
      dimensions: '38x25x2 cm',
      weight: 2.5,
    ),
    const Product(
      id: '10',
      name: 'Running Shoes',
      price: 79.99,
      imageUrl: 'assets/images/running shoes.jpg',
      category: 'Clothing',
      rating: 4.3,
      description: 'Lightweight and breathable running shoes for long-distance comfort.',
      brand: 'SpeedStride',
      model: 'SS-Runner',
      dimensions: '30x15x10 cm',
      weight: 0.8,
    ),
    const Product(
      id: '11',
      name: 'Smartphone with Advanced Camera Features',
      price: 799.99,
      imageUrl: 'assets/images/smartphone.jpg',
      category: 'Electronics',
      rating: 4.7,
      description: 'Flagship smartphone equipped with a high-resolution camera and ultra-fast processor.',
      brand: 'TechNova',
      model: 'TN-Ultra',
      dimensions: '16x7x0.8 cm',
      weight: 0.3,
    ),
    const Product(
      id: '12',
      name: 'Smart Watch',
      price: 149.99,
      imageUrl: 'assets/images/smartwatch.jpeg',
      category: 'Electronics',
      rating: 4.7,
      description: 'Advanced smartwatch with heart rate monitoring, GPS, and fitness tracking.',
      brand: 'SmartFit',
      model: 'SF-Pro',
      dimensions: '4x4x1 cm',
      weight: 0.1,
    ),
    const Product(
      id: '13',
      name: 'Bluetooth Speaker',
      price: 59.99,
      imageUrl: 'assets/images/speaker.jpg',
      category: 'Electronics',
      rating: 4.7,
      description: 'Portable Bluetooth speaker delivering immersive 360° surround sound.',
      brand: 'SoundWave',
      model: 'SW-360',
      dimensions: '18x10x10 cm',
      weight: 0.8,
    ),
    const Product(
      id: '14',
      name: 'Organic Green Tea',
      price: 14.99,
      imageUrl: 'assets/images/tea.jpg',
      category: 'Health & Wellness',
      rating: 4.8,
      description: 'Premium organic green tea known for its calming effects and rich antioxidants.',
      brand: 'NatureBrew',
      model: 'NB-GreenTea',
      dimensions: '10x10x15 cm',
      weight: 0.5,
    ),
    const Product(
      id: '15',
      name: 'Graphic T-Shirt',
      price: 19.99,
      imageUrl: 'assets/images/tshirt.jpeg',
      category: 'Clothing',
      rating: 4.5,
      description: 'Stylish cotton graphic T-shirt with a trendy design.',
      brand: 'FashionWear',
      model: 'FW-PrintX',
      dimensions: '30x25x1 cm',
      weight: 0.2,
    ),
    const Product(
      id: '16',
      name: 'Premium Leather Wallet',
      price: 39.99,
      imageUrl: 'assets/images/wallet.PNG',
      category: 'Accessories',
      rating: 4.4,
      description: 'Elegant leather wallet designed with RFID protection for security.',
      brand: 'LuxWallet',
      model: 'LW-RFID',
      dimensions: '11x9x2 cm',
      weight: 0.2,
    ),
    const Product(
      id: '17',
      name: 'Wireless Mouse',
      price: 29.99,
      imageUrl: 'assets/images/wireless.jpeg',
      category: 'Computers',
      rating: 4.6,
      description: 'Ergonomic wireless mouse with customizable buttons and fast response time.',
      brand: 'ClickMaster',
      model: 'CM-X200',
      dimensions: '12x6x4 cm',
      weight: 0.15,
    ),
    const Product(
      id: '18',
      name: 'Yoga Mat',
      price: 34.99,
      imageUrl: 'assets/images/yogamat.jpeg',
      category: 'Sports & Fitness',
      rating: 4.5,
      description: 'Durable and cushioned yoga mat designed for superior grip and comfort.',
      brand: 'FlexFlow',
      model: 'FF-MatX',
      dimensions: '180x60x0.6 cm',
      weight: 1.2,
    ),
  ];
});

final preferenceServiceProvider = Provider<PreferenceService>((ref) {
  return PreferenceServiceFactory.create();
});