analyzer:
  enable-experiment:
    - sealed
  errors:
    # Enable additional error checks
    cancel_subscriptions: error
    close_sinks: error
    deprecated_member_use: error
    empty_catches: error
    implementation_imports: error
    invalid_override: error
    missing_required_param: error
    non_abstract_class_inherits_abstract_member: error
    prefer_final_fields: error
    prefer_initializing_formals: error
    prefer_spread_collections: error
    type_annotate_public_apis: error
    unused_element: error
    unused_field: error
    unused_import: error
    unused_label: error
    unused_local_variable: error
    unused_parameter: error
    unused_shown_name: error

linter:
  rules:
    # Enable additional lint rules
    - avoid_shadowing_type_parameters
    - camel_case_types
    - comment_references
    - empty_constructor_bodies
    - file_names
    - library_names
    - lines_longer_than_80_chars
    - non_constant_identifier_names
    - prefer_adjacent_string_concatenation
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_constructors_over_static_methods
    - prefer_final_locals
    - prefer_interpolation_to_compose_strings
    - prefer_single_quotes
    - slash_for_doc_comments
    - sort_child_properties_last
    - type_init_formals
    - valid_regexps
    - avoid_catches_without_on_clauses
    - avoid_function_literals_in_foreach_calls
    - avoid_types_as_parameter_names
    - camel_case_extensions
    - curly_braces_in_flow_control_structures
    - empty_statements
    - equality_unnecessary_operands
    - implementation_imports
    - invalid_assignment
    - list_remove_unrelated_type
    - missing_default_case
    - no_logic_in_create_state
    - prefer_contains
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_null_aware_operations
    - prefer_single_file_library_declarations
    - recursive_getters
    - unrelated_type_equality_checks
    - unnecessary_this
    - use_full_hex_values_for_flutter_colors
    - valid_constructor_name
    - avoid_bool_literals_in_conditional_expressions
    - avoid_equal_checks_in_equality_operators
    - avoid_null_checks_in_equality_operators
    - avoid_positional_boolean_parameters
    - avoid_redundant_argument_values
    - avoid_renaming_method_parameters
    - avoid_returning_null_for_future
    - avoid_returning_null_for_void
    - avoid_set_of_nullable_type
    - avoid_unnecessary_containers
    - avoid_unnecessary_containers
    - avoid_unused_container_children
    - avoid_void_async
    - camel_case_types
    - cascade_invocations
    - comment_references
    - constant_identifier_names
    - deprecated_member_use_from_same_package
    - diagnostic_describe_all_properties
    - empty_constructor_bodies
    - empty_statements
    - file_names
    - flutter_style_todos
    - lines_longer_than_80_chars
    - member_ordering
    - missing_whitespace_between_adjacent_strings
    - no_duplicate_case_values
    - non_constant_identifier_names
    - omit_local_variable_types
    - prefer_asserts_in_initializer_lists
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_equatable_to_override_toString
    - prefer_expression_function_bodies
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_interpolation_to_compose_strings
    - prefer_single_quotes
    - require_trailing_commas
    - sort_child_properties_last
    - type_annotate_public_apis
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_overrides
    - unnecessary_this
    - unrelated_type_equality_checks
    - use_build_context_synchronously
    - use_decorated_box
    - use_full_hex_values_for_flutter_colors
    - use_string_buffers
    - valid_regexps
    - avoid_catches_without_on_clauses
    - avoid_function_literals_in_foreach_calls
    - avoid_types_as_parameter_names
    - camel_case_extensions
    - curly_braces_in_flow_control_structures
    - empty_statements
    - equality_unnecessary_operands
    - implementation_imports
    - invalid_assignment
    - list_remove_unrelated_type
    - missing_default_case
    - no_logic_in_create_state
    - prefer_contains
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_null_aware_operations
    - prefer_single_file_library_declarations
    - recursive_getters
    - unrelated_type_equality_checks
    - unnecessary_this
    - use_full_hex_values_for_flutter_colors
    - valid_constructor_name